# Generated by Django 5.2.5 on 2025-08-22 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('mood', models.CharField(blank=True, max_length=50)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('water_glasses', models.IntegerField(blank=True, null=True)),
                ('exercise', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='journal_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
