# Generated by Django 5.2.5 on 2025-09-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullet_journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='mood',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='journal',
            name='sleep_hours',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='journal',
            name='water_glasses',
            field=models.IntegerField(null=True),
        ),
    ]
