# Generated by Django 5.2.5 on 2025-09-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bullet_journal', '0002_alter_journal_content_alter_journal_mood_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='content',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='title',
        ),
    ]
