# Generated by Django 5.2.5 on 2025-09-25 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullet_journal', '0003_remove_journal_content_remove_journal_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('boolean', 'Sí/No'), ('integer', 'Número'), ('float', 'Número Decimal')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_habits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatsPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('mood', 'Estado de ánimo'), ('sleep_hours', 'Horas de sueño'), ('water_glasses', 'Vasos de agua'), ('exercise', 'Ejercicio')], max_length=50)),
                ('period', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('yearly', 'Anual')], default='weekly', max_length=10)),
                ('chart_type', models.CharField(choices=[('line', 'Línea'), ('bar', 'Barra'), ('pie', 'Pastel')], default='line', max_length=10)),
                ('is_visible', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('user', 'field')},
            },
        ),
    ]
