# Generated by Django 5.2.5 on 2025-09-30 20:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullet_journal', '0005_journal_custom_habits_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customhabit',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='customhabit',
            name='goal_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customhabit',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customhabit',
            name='type',
            field=models.CharField(choices=[('boolean', 'Sí/No'), ('integer', 'Número')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='customhabit',
            unique_together={('user', 'name')},
        ),
        migrations.DeleteModel(
            name='HabitTracking',
        ),
    ]
