# Generated by Django 5.2.5 on 2025-10-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullet_journal', '0006_alter_customhabit_options_customhabit_goal_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='diary_entry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='diary_image',
            field=models.ImageField(blank=True, null=True, upload_to='diary_images/'),
        ),
        migrations.AddField(
            model_name='journal',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
